import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { listConnections } from './connections.js';
import { readPeerSummaryCache, type PeerSummary } from './federation-peer-summary.js';
import { resolveVaultContextRoot } from './vaults.js';

/**
 * PER-PEER SUBAGENTS — a connection becomes something the agent can address.
 *
 * A connection in `.connections.json` is invisible to the model: it changes what
 * recall returns, but nothing tells the agent "there is a project called Tilki
 * and you may ask it things." So for every active connection we GENERATE a
 * subagent file — `.claude/agents/peer-<slug>.md` — carrying that peer's
 * identity glance and the exact commands that reach it.
 *
 * Generated, never hand-written, and regenerated on every connect / disconnect /
 * sleep cycle: the peer's identity is a moving target (its soul, its active
 * task, its pinned docs all drift), and a stale hand-edited copy would brief the
 * agent about a project that no longer exists in that shape. Files carry a
 * generated-by marker and this generator OWNS the `peer-*.md` namespace — it
 * deletes the ones whose connection is gone, so disconnecting actually removes
 * the agent's ability to address that vault instead of leaving a dead pointer.
 *
 * Why a subagent rather than a line in the skill: asking a peer means reading a
 * long answer built from a corpus this vault does not have. That belongs in its
 * own context window, returning the conclusion — which is exactly what a
 * subagent is for.
 */

/** Marker line that identifies a file this generator owns. */
const GENERATED_MARKER = '<!-- generated by dreamcontext: peer agent (do not edit) -->';

/** Filename prefix owned by this generator. */
const PEER_AGENT_PREFIX = 'peer-';

/**
 * Slugify a vault name into a filename-safe agent id. Collapses anything outside
 * `[a-z0-9-]` so a vault named "Tilki Öğretmen" cannot produce a path component
 * that needs quoting (or escapes the directory).
 */
export function peerAgentSlug(vault: string): string {
  const slug = vault
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
  return slug || 'peer';
}

/** `.claude/agents/` for a project root. */
export function agentsDir(projectRoot: string): string {
  return join(projectRoot, '.claude', 'agents');
}

export interface PeerAgentInput {
  vault: string;
  /** Absolute path to the peer's project root — the agent's "where it lives". */
  projectRoot: string;
  /** Identity glance from the peer-summary cache, when one exists. */
  summary: PeerSummary | null;
}

/**
 * Render the subagent markdown for one peer.
 *
 * The `description` is what the main agent routes on, so it names the peer, what
 * it is, and the situations that should reach for it — a description that just
 * said "talks to a peer" would never be selected at the right moment.
 */
export function renderPeerAgent(input: PeerAgentInput): string {
  const { vault, projectRoot, summary } = input;
  const whatItIs = summary?.whatItIs?.trim() ?? '';
  const tags = summary?.topTags ?? [];
  const pinned = summary?.pinnedKnowledge ?? [];
  const activeTask = summary?.activeTask?.trim() ?? '';
  const lastActivity = summary?.lastActivity ?? [];

  const descriptionLines = [
    `Speaks to "${vault}", a connected dreamcontext project on this machine.`,
    whatItIs ? `That project is: ${whatItIs}` : '',
    `Use when a question is really about ${vault} rather than this project —`,
    `its code, its decisions, its history — or when ${vault} needs to be told`,
    'something or asked to do something. It answers with ITS OWN brain loaded,',
    'so it knows things this project has no copy of.',
    tags.length ? `Its subjects: ${tags.join(', ')}.` : '',
  ].filter(Boolean);

  const context: string[] = [];
  if (whatItIs) context.push(`- **What it is**: ${whatItIs}`);
  context.push(`- **Where it lives**: \`${projectRoot}\``);
  if (activeTask) context.push(`- **Currently working on**: ${activeTask}`);
  if (lastActivity.length) {
    context.push(`- **Recently**: ${lastActivity.join(' · ')}`);
  }
  if (tags.length) context.push(`- **Subjects**: ${tags.join(', ')}`);
  if (pinned.length) {
    context.push(`- **Its canonical docs**: ${pinned.join(' · ')}`);
  }

  return `---
name: peer-${peerAgentSlug(vault)}
description: >
${descriptionLines.map((l) => `  ${l}`).join('\n')}
tools: Bash, Read, Grep, Glob
skills:
  - dreamcontext
---

${GENERATED_MARKER}

# Peer — ${vault}

You are this project's envoy to **${vault}**, a separate dreamcontext project on
this machine that this project is connected to.

## What ${vault} is

${context.join('\n')}

## How to reach it

Everything goes through \`dreamcontext peer\`. You do NOT cd into ${vault}, you do
NOT read its files directly, and you do NOT edit anything there. That project has
its own agent, its own constraints, and its own idea of what is true — your job
is to ask it, not to reach around it.

\`\`\`bash
# Ask a question and wait for the answer (spawns ${vault}'s own agent, ~30-90s)
dreamcontext peer ask ${vault} "your question"

# Leave a note — no spawn, it reads it when it next wakes
dreamcontext peer send ${vault} "your note" --kind note

# Hand over work. Runs under \`auto\` permissions there, never bypass.
dreamcontext peer send ${vault} "what to do" --kind command

# The correspondence
dreamcontext peer inbox
dreamcontext peer thread <id>
dreamcontext peer reply <id> "your reply"
\`\`\`

For a cheap read with no spawn at all, recall reads ${vault}'s canonical docs live:

\`\`\`bash
dreamcontext memory recall "<query>" --vault ${vault}
\`\`\`

## Choosing between them

**Recall** when you want to find what ${vault} has WRITTEN DOWN — a decision, a
doc, a task. It is fast, free, and returns the source text.

**Ask** when the answer has to be REASONED from that project's code and context:
"where is X implemented", "why was Y done this way", "would Z break anything
there". Recall returns documents; asking returns an answer, and ${vault}'s agent
can read its own code to produce one.

**Send a command** only when the user actually wants work done in ${vault}. Say
plainly in your report that work was requested in another project.

## Reporting back

Return what ${vault} said, attributed. Do not launder its answer into your own
voice — if ${vault} said something surprising or contradicts what this project
believes, that contradiction is the finding, and flattening it hides the one
thing worth knowing. If it could not answer, say that rather than filling the
gap with a guess of your own.
`;
}

export interface SyncPeerAgentsResult {
  written: string[];
  removed: string[];
}

/**
 * Regenerate the `peer-*.md` agents for a project so they match its ACTIVE
 * connections exactly: one file per active peer, and no file for anything else.
 *
 * Idempotent and safe to call on every connect / disconnect / sleep / install.
 * NEVER throws — a failure to write an agent file must not fail the command that
 * triggered it (you asked to connect; a briefing file is a side effect).
 *
 * Only files carrying {@link GENERATED_MARKER} are removed, so a hand-written
 * agent that happens to be named `peer-something.md` is left alone rather than
 * silently deleted.
 */
export function syncPeerAgents(contextRoot: string, home?: string): SyncPeerAgentsResult {
  const result: SyncPeerAgentsResult = { written: [], removed: [] };
  const projectRoot = dirname(contextRoot);
  const dir = agentsDir(projectRoot);

  let active: string[] = [];
  try {
    active = listConnections(contextRoot)
      .filter((c) => c.status !== 'stale')
      .map((c) => c.vault);
  } catch {
    return result;
  }

  const cache = readPeerSummaryCache(contextRoot);
  const summaryOf = (vault: string): PeerSummary | null =>
    cache?.peers.find((p) => p.vault === vault) ?? null;

  const expected = new Set<string>();
  for (const vault of active) {
    let peerProjectRoot: string;
    try {
      peerProjectRoot = dirname(resolveVaultContextRoot(vault, home));
    } catch {
      // A peer whose path went away gets no agent — an envoy to a vault that is
      // not there would fail on every call and read as a broken tool.
      continue;
    }
    const file = `${PEER_AGENT_PREFIX}${peerAgentSlug(vault)}.md`;
    expected.add(file);
    try {
      mkdirSync(dir, { recursive: true });
      writeFileSync(
        join(dir, file),
        renderPeerAgent({ vault, projectRoot: peerProjectRoot, summary: summaryOf(vault) }),
        'utf-8',
      );
      result.written.push(file);
    } catch {
      // best-effort
    }
  }

  // Retire agents for peers that are no longer connected.
  if (existsSync(dir)) {
    let files: string[] = [];
    try {
      files = readdirSync(dir).filter(
        (f) => f.startsWith(PEER_AGENT_PREFIX) && f.endsWith('.md') && !expected.has(f),
      );
    } catch {
      return result;
    }
    for (const file of files) {
      const path = join(dir, file);
      try {
        // Ours to delete only if we wrote it.
        const body = readFileSyncSafe(path);
        if (body === null || !body.includes(GENERATED_MARKER)) continue;
        rmSync(path, { force: true });
        result.removed.push(file);
      } catch {
        // best-effort
      }
    }
  }

  return result;
}

/** Read a file, returning null instead of throwing on any failure. */
function readFileSyncSafe(path: string): string | null {
  try {
    return readFileSync(path, 'utf-8');
  } catch {
    return null;
  }
}
