// Auto-generated by scripts/generate-banner.mjs — do not edit manually
import chalk from 'chalk';

const P: [number, number, number][] = [[160,160,200],[160,200,200],[160,200,240],[120,160,240],[120,160,200],[120,200,240],[160,160,240],[80,160,200],[200,240,240],[240,240,240],[200,200,240],[200,240,200],[160,240,240],[80,120,200],[40,160,200],[40,120,200],[120,200,200],[40,120,160],[80,80,120],[40,80,120],[240,240,160],[200,200,200],[80,200,200],[80,200,240],[80,160,240],[80,120,120],[120,120,120],[40,80,160],[40,120,120],[200,120,120],[0,40,40],[0,0,40],[120,120,160],[160,120,120],[240,160,120],[200,160,120],[80,80,80],[40,80,80],[240,200,160],[200,160,160],[80,120,160],[40,40,80],[40,40,40],[0,40,80],[120,160,160],[240,240,200],[240,160,160],[120,80,120],[160,160,160],[160,80,120],[120,80,80],[240,200,200]];
const D = [
  '........................001................................',
  '.................2222.0222202..............................',
  '................22223434444420.............................',
  '............222225244344344466..66.........................',
  '...........22222255447289844444............................',
  '..........a22bb523754775844444444...2......................',
  '.........a222b1552c92729827719240002a2.....................',
  '......a2.22225555228775254d49add10222aa....................',
  '......888.2225525e88c4fdddd690d4d402222a...................',
  '......222..255c8572g7fddd4d49a474444122aa..................',
  '.........55..55827efhijddddd288a4d74kl2aaa.................',
  '........5c5..m5cnohjpqqr40ddd444d444l12aaa.................',
  '.........44....nnsiqittj74da2d44444402122..................',
  '..........53.uvvuiwixyzAdd48a43.640000.....................',
  '..........uBiqwqqwpqCDzA...dE..F..4a.......................',
  '.GFFFGH.uiqwIwqqqqqJ9DDA..uFAipppiBv.......................',
  'FpwwwwwiqwqqqqqqqqwJJKDiuiqqqwwwqwIIpF.....................',
  'FLipqqqwqqqqqqqqqqqwMxDAFiAAiiiiiqwIMMiu...................',
  'FNOApqqqqqMlqqqqqqqqqqqiBFAAiippqpppqqIwF..................',
  'vOtABpqqqq09wqqwwwwwwqqwqBBiiqiipqwqqqpwwF.................',
  '.FtOFiqqqq090qwwwwwwwwqqpFBppiqMwqqqqqqpqqu................',
  '.vqxBqqqqq099wwwwwwwwwqqwFAqiwlqqqqqqqqqpwA................',
  '..Fxiqqqqq099lqwwIqqwwwwqAiiqlwqqqqqqqqqiipF...............',
  '...FpqqqqqM999lwiAFqwMMwBBpAlMqqqqqqqpipiAiB...............',
  '...FqqqqqqM99999MMMIMMwiFiiplqqqqqqqpiiiiAABv..............',
  '...Fqqqwwww99J999999l0MBFABq1qqqqqqqiiiAAAiiF..............',
  '...iwqqAAFM9Ky9999999liq1MBiMqqpqpiiiiiAiAiqwF.............',
  '..Fqqqqiil999Mll9990MMl999IBqAiiiiiiiiiiBFpiqAv............',
  '..FFiqqw0llJl0P99MMl9999lwpiiiABBAAAAABFFipiiiv............',
  '...uBiBpM0MqM99lM999999MFiwwqqqwqiAAAAAipiAAAAu............',
  '.....ui99999wMwq999999lGBAAAAAiqwwqpqqwqiiABFGv............',
  '....aIi9999lquvIl9l98lwuBBAAAiiqqqqiAiqqpAFFup0............',
  '....01IqMwMAq0IpqMI0piiGuFFFFAipqqqiiiiiBFGuq10............',
  '......lMqqwMlllMpiipI110FuGFFBiiiiiiAFFGGFAw1..............',
  '......................010wAFFFAABFFFFFFFiw1................',
  '..........................lIpABBBBBAip.....................',
];

const IDX: Record<string, number> = {};
'0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('').forEach((c, i) => { IDX[c] = i; });

function decodeIdx(c: string): number {
  return c === '.' ? -1 : IDX[c];
}

export function renderBanner(): string {
  const lines: string[] = [];
  for (let y = 0; y < D.length; y += 2) {
    let line = '';
    const topRow = D[y];
    const botRow = D[y + 1];
    for (let x = 0; x < topRow.length; x++) {
      const ti = decodeIdx(topRow[x]);
      const bi = decodeIdx(botRow[x]);
      if (ti === -1 && bi === -1) {
        line += ' ';
      } else if (ti >= 0 && bi === -1) {
        const [r, g, b] = P[ti];
        line += chalk.rgb(r, g, b)('\u2580');
      } else if (ti === -1 && bi >= 0) {
        const [r, g, b] = P[bi];
        line += chalk.rgb(r, g, b)('\u2584');
      } else {
        const [tr, tg, tb] = P[ti];
        const [br, bg, bb] = P[bi];
        if (tr === br && tg === bg && tb === bb) {
          line += chalk.rgb(tr, tg, tb)('\u2588');
        } else {
          line += chalk.rgb(tr, tg, tb).bgRgb(br, bg, bb)('\u2580');
        }
      }
    }
    lines.push('    ' + line);
  }
  return lines.join('\n');
}
