import { createHash } from 'node:crypto';

/**
 * The hands-free cloud's service worker (AC16), served at `/handsfree-sw.js` by
 * `handsfree-login.ts` and registered by the phone's CloudChip once the cloud answers.
 *
 * W0 item 10 (real iPhone) fixed every rule here:
 *  - GitHub's forwarder serves a 'Codespaces Access Port' interstitial (200 HTML, no
 *    X-Dreamcontext-Cloud) to browser navigations on a public port; the header
 *    `X-Tunnel-Skip-AntiPhishing-Page: true` skips it, so every navigation is re-issued with it.
 *  - A response carrying our `X-Dreamcontext-Cloud` passes through untouched, whatever its status.
 *  - Only a 404/502/503/504 or a network error WITHOUT our header means "asleep", and only
 *    after retries: a transient forwarder hang on a RUNNING machine made the first spike show
 *    a false asleep page.
 *  - Only the offline page is cached (install time, versioned, old caches deleted).
 *  - Never /api/*, /login, the WebSocket or assets: only top-level navigations.
 */

export const SKIP_HEADER = 'X-Tunnel-Skip-AntiPhishing-Page';
export const CLOUD_HEADER = 'X-Dreamcontext-Cloud';
export const OFFLINE_PATH = '/handsfree-offline.html';
export const SW_PATH = '/handsfree-sw.js';
/** Per-attempt timeouts: one try plus two retries (W0: the forwarder hangs ~15 s at times). */
export const ATTEMPT_TIMEOUTS_MS: readonly number[] = [8000, 5000, 5000];

export type SwVerdict = 'pass' | 'retry' | 'offline';

export interface SwAttempt {
  /** 1-based attempt number. */
  attempt: number;
  maxAttempts: number;
  /** null for a network error (fetch threw, or the attempt timed out). */
  status: number | null;
  /** The response carried `X-Dreamcontext-Cloud`. */
  hasCloudHeader: boolean;
}

/**
 * Pure: what the SW does with one attempt's outcome. Self-contained on purpose: its source is
 * embedded verbatim into the service worker script (no imports, no outer constants).
 */
export function swDecide(a: SwAttempt): SwVerdict {
  if (a.status !== null && a.hasCloudHeader) return 'pass';
  const asleep = a.status === null || a.status === 404 || a.status === 502 || a.status === 503 || a.status === 504;
  if (!asleep) return 'pass';
  return a.attempt < a.maxAttempts ? 'retry' : 'offline';
}

/** Pure: does the SW handle this request at all? Only same-origin top-level navigations. */
export function swIntercepts(mode: string, url: string, origin: string): boolean {
  if (mode !== 'navigate') return false;
  let u: URL;
  try { u = new URL(url); } catch { return false; }
  if (u.origin !== origin) return false;
  const p = u.pathname;
  if (p === '/api' || p.startsWith('/api/')) return false;
  if (p === '/login' || p.startsWith('/login/')) return false;
  if (p === '/handsfree-sw.js' || p === '/handsfree-offline.html' || p === '/manifest.webmanifest') return false;
  return true;
}

/** The service worker script. `version` names the cache (the offline page's hash). */
export function serviceWorkerSource(version: string): string {
  return `// dreamcontext hands-free service worker (AC16). Generated by the cloud server.
'use strict';
const CACHE = ${JSON.stringify(`dc-hf-offline-${version}`)};
const OFFLINE = ${JSON.stringify(OFFLINE_PATH)};
const SKIP = ${JSON.stringify(SKIP_HEADER)};
const CLOUD = ${JSON.stringify(CLOUD_HEADER)};
const TIMEOUTS = ${JSON.stringify(ATTEMPT_TIMEOUTS_MS)};
const decide = (${swDecide.toString()});
const intercepts = (${swIntercepts.toString()});

async function attempt(url, accept, timeoutMs) {
  const ctl = new AbortController();
  const timer = setTimeout(() => ctl.abort(), timeoutMs);
  try {
    const headers = { [SKIP]: 'true' };
    if (accept) headers.Accept = accept;
    // redirect 'manual': a navigation may only be answered with an unfollowed redirect.
    return await fetch(url, { headers, credentials: 'include', cache: 'no-store', redirect: 'manual', signal: ctl.signal });
  } catch {
    return null;
  } finally {
    clearTimeout(timer);
  }
}

async function navigate(request) {
  const accept = request.headers.get('Accept') || 'text/html';
  let last = null;
  for (let i = 1; i <= TIMEOUTS.length; i++) {
    const res = await attempt(request.url, accept, TIMEOUTS[i - 1]);
    if (res) last = res;
    const verdict = decide({
      attempt: i,
      maxAttempts: TIMEOUTS.length,
      status: res ? res.status : null,
      hasCloudHeader: !!(res && res.headers.get(CLOUD)),
    });
    if (verdict === 'pass') return res;
    if (verdict === 'offline') break;
    await new Promise((r) => setTimeout(r, 400 * i));
  }
  const cached = await caches.match(OFFLINE, { cacheName: CACHE });
  return cached || last || Response.error();
}

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    for (let i = 0; i < 3; i++) {
      const res = await attempt(OFFLINE, '*/*', 10000);
      if (res && res.ok && res.headers.get(CLOUD)) { await cache.put(OFFLINE, res); return; }
      await new Promise((r) => setTimeout(r, 1000 * (i + 1)));
    }
    throw new Error('offline page unavailable');
  })());
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) if (key !== CACHE) await caches.delete(key);
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const r = event.request;
  if (!intercepts(r.mode, r.url, self.location.origin)) return;
  event.respondWith(navigate(r));
});
`;
}

/** A short content hash, used to version the offline cache. */
export function shortHash(...parts: string[]): string {
  const h = createHash('sha256');
  for (const p of parts) h.update(p).update('\0');
  return h.digest('hex').slice(0, 12);
}
