#!/usr/bin/env node
/**
 * Converts the agentcontext logo PNG into a compact pixel-art data format
 * that can be rendered in the terminal using half-block characters + chalk.rgb().
 *
 * Usage: node scripts/generate-banner.mjs
 */
import sharp from 'sharp';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const INPUT = join(__dirname, '..', 'public', 'image', 'dreamcontext.png');

const TARGET_WIDTH = 44; // terminal columns
const QUANT_STEP = 40;   // color quantization step (lower = more colors, higher = fewer)

async function main() {
  const img = sharp(INPUT);
  const meta = await img.metadata();

  // Calculate height maintaining aspect ratio
  // Each terminal char is ~2x tall as wide, so divide height by 2
  const aspectRatio = meta.height / meta.width;
  let pixelHeight = Math.round(TARGET_WIDTH * aspectRatio);
  if (pixelHeight % 2 !== 0) pixelHeight += 1; // even for half-block pairing

  const { data } = await img
    .resize(TARGET_WIDTH, pixelHeight, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });

  // Build palette with quantized colors
  const colorMap = new Map();
  const pixels = []; // flat array of palette indices (-1 = transparent)

  for (let i = 0; i < data.length; i += 4) {
    const r = data[i], g = data[i + 1], b = data[i + 2], a = data[i + 3];

    if (a < 64) {
      pixels.push(-1);
    } else {
      const qr = Math.round(r / QUANT_STEP) * QUANT_STEP;
      const qg = Math.round(g / QUANT_STEP) * QUANT_STEP;
      const qb = Math.round(b / QUANT_STEP) * QUANT_STEP;
      const key = `${qr},${qg},${qb}`;

      if (!colorMap.has(key)) {
        colorMap.set(key, colorMap.size);
      }
      pixels.push(colorMap.get(key));
    }
  }

  const palette = Array.from(colorMap.keys()).map((k) => k.split(',').map(Number));

  console.error(`Image: ${meta.width}x${meta.height} → ${TARGET_WIDTH}x${pixelHeight} pixels → ${TARGET_WIDTH}x${pixelHeight / 2} char rows`);
  console.error(`Palette: ${palette.length} colors`);

  if (palette.length > 62) {
    console.error('WARNING: palette too large, increase QUANT_STEP');
    process.exit(1);
  }

  // Encode pixel grid as compact strings
  // Index chars: 0-9 (0-9), a-z (10-35), A-Z (36-61), '.' for transparent
  const encodeIdx = (idx) => {
    if (idx === -1) return '.';
    if (idx < 10) return String(idx);
    if (idx < 36) return String.fromCharCode(97 + idx - 10); // a-z
    return String.fromCharCode(65 + idx - 36); // A-Z
  };

  const rows = [];
  for (let y = 0; y < pixelHeight; y++) {
    let row = '';
    for (let x = 0; x < TARGET_WIDTH; x++) {
      row += encodeIdx(pixels[y * TARGET_WIDTH + x]);
    }
    rows.push(row);
  }

  // Trim empty rows from top and bottom
  let topTrim = 0;
  while (topTrim < rows.length && rows[topTrim].replace(/\./g, '') === '') topTrim++;
  let botTrim = rows.length;
  while (botTrim > topTrim && rows[botTrim - 1].replace(/\./g, '') === '') botTrim--;

  // Make sure we have even number of rows
  const trimmedRows = rows.slice(topTrim, botTrim);
  if (trimmedRows.length % 2 !== 0) trimmedRows.push('.'.repeat(TARGET_WIDTH));

  // Also trim empty columns from left
  let leftTrim = TARGET_WIDTH;
  for (const row of trimmedRows) {
    const first = row.search(/[^.]/);
    if (first >= 0 && first < leftTrim) leftTrim = first;
  }
  const finalRows = trimmedRows.map((r) => r.slice(leftTrim));
  const finalWidth = TARGET_WIDTH - leftTrim;

  console.error(`After trim: ${finalWidth}x${finalRows.length} pixels → ${finalWidth}x${finalRows.length / 2} char rows`);

  // Output TypeScript source
  const paletteStr = palette.map(([r, g, b]) => `[${r},${g},${b}]`).join(',');

  console.log(`// Auto-generated by scripts/generate-banner.mjs — do not edit manually`);
  console.log(`import chalk from 'chalk';`);
  console.log(``);
  console.log(`const P: [number, number, number][] = [${paletteStr}];`);
  console.log(`const D = [`);
  for (const row of finalRows) {
    console.log(`  '${row}',`);
  }
  console.log(`];`);
  console.log(``);
  console.log(`const IDX: Record<string, number> = {};`);
  console.log(`'0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('').forEach((c, i) => { IDX[c] = i; });`);
  console.log(``);
  console.log(`function decodeIdx(c: string): number {`);
  console.log(`  return c === '.' ? -1 : IDX[c];`);
  console.log(`}`);
  console.log(``);
  console.log(`export function renderBanner(): string {`);
  console.log(`  const lines: string[] = [];`);
  console.log(`  for (let y = 0; y < D.length; y += 2) {`);
  console.log(`    let line = '';`);
  console.log(`    const topRow = D[y];`);
  console.log(`    const botRow = D[y + 1];`);
  console.log(`    for (let x = 0; x < topRow.length; x++) {`);
  console.log(`      const ti = decodeIdx(topRow[x]);`);
  console.log(`      const bi = decodeIdx(botRow[x]);`);
  console.log(`      if (ti === -1 && bi === -1) {`);
  console.log(`        line += ' ';`);
  console.log(`      } else if (ti >= 0 && bi === -1) {`);
  console.log(`        const [r, g, b] = P[ti];`);
  console.log(`        line += chalk.rgb(r, g, b)('\\u2580');`);
  console.log(`      } else if (ti === -1 && bi >= 0) {`);
  console.log(`        const [r, g, b] = P[bi];`);
  console.log(`        line += chalk.rgb(r, g, b)('\\u2584');`);
  console.log(`      } else {`);
  console.log(`        const [tr, tg, tb] = P[ti];`);
  console.log(`        const [br, bg, bb] = P[bi];`);
  console.log(`        if (tr === br && tg === bg && tb === bb) {`);
  console.log(`          line += chalk.rgb(tr, tg, tb)('\\u2588');`);
  console.log(`        } else {`);
  console.log(`          line += chalk.rgb(tr, tg, tb).bgRgb(br, bg, bb)('\\u2580');`);
  console.log(`        }`);
  console.log(`      }`);
  console.log(`    }`);
  console.log(`    lines.push('    ' + line);`);
  console.log(`  }`);
  console.log(`  return lines.join('\\n');`);
  console.log(`}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
